base_config: delta_sft_base.yaml
run_id: ace_ego_0_arx_scan_pencil_case_new_delta_sft
datasets:
  vla_data:
    dataset_manifest_path: manifests/scan_pencil_case_new.txt
    norm_manifest_path: ${datasets.vla_data.data_root_dir}/norm/scan_pencil_case_new/delta/norm_manifest.json
